name:                win2unix
version:             0.1.0.0
github:              "alexanderjdupree/win2unix"
license:             BSD3
author:              "Alexander DuPree"
maintainer:          "alexander.j.dupree@gmail.com"
copyright:           "2019 Alexander DuPree"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexanderjdupree/win2unix#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  win2unix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - win2unix

tests:
  win2unix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - win2unix
